apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-05-pvc
  namespace: django-test-05
  labels:
    app: django-test-05
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
