apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-22-pvc
  namespace: django-test-22
  labels:
    app: django-test-22
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
