apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-21-pvc
  namespace: django-test-21
  labels:
    app: django-test-21
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
