apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-api-pvc
  namespace: django-api
  labels:
    app: django-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

