apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-02-pvc
  namespace: django-test-02
  labels:
    app: django-test-02
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
