apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-09-pvc
  namespace: django-test-09
  labels:
    app: django-test-09
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
