apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-06-pvc
  namespace: django-test-06
  labels:
    app: django-test-06
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
