apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-08-pvc
  namespace: django-test-08
  labels:
    app: django-test-08
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
