apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-10-pvc
  namespace: django-test-10
  labels:
    app: django-test-10
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
