apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

# commonLabels không áp dụng cho selector (immutable)
# Chỉ áp dụng cho metadata labels
commonLabels:
  version: v1.0.0
  managed-by: dev-portal

# Loại bỏ commonLabels khỏi selector để tránh lỗi immutable
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: django-api-staging
  spec:
    selector:
      matchLabels:
        app: django-api-staging

namespace: django-api-staging
