apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

# Sử dụng labels thay vì commonLabels (deprecated)
labels:
- pairs:
    version: v1.0.0
    managed-by: dev-portal

# Sử dụng patches thay vì patchesStrategicMerge (deprecated)
patches:
- target:
    kind: Deployment
    name: django-api-staging
  patch: |-
    - op: replace
      path: /spec/selector
      value:
        matchLabels:
          app: django-api-staging

namespace: django-api-staging
