apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-03-pvc
  namespace: django-test-03
  labels:
    app: django-test-03
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
