apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-20-pvc
  namespace: django-test-20
  labels:
    app: django-test-20
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
