apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-07-pvc
  namespace: django-test-07
  labels:
    app: django-test-07
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
