apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-25-pvc
  namespace: django-test-25
  labels:
    app: django-test-25
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
