apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: django-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/quanmbl4255142/repository_b_ci_cd_fpt_repob_devops.git
      revision: main
      directories:
      - path: apps/*
      # Tối ưu: Refresh nhanh hơn để detect app mới sớm hơn
      refresh: 30s
  template: 
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/quanmbl4255142/repository_b_ci_cd_fpt_repob_devops.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
      revisionHistoryLimit: 3

