apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-webhook-config
  namespace: argocd
data:
  webhook.yaml: |
    # GitHub Webhook configuration for ArgoCD
    # This will trigger ArgoCD sync when Repository_B is updated
    
    # Webhook URL: https://your-argocd-domain.com/api/webhooks/github
    # Secret: your-webhook-secret
    
    # Events to trigger:
    # - push to main branch
    # - changes in apps/ directory
    
    # ArgoCD will automatically sync applications when webhook is triggered
