apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-11-pvc
  namespace: django-test-11
  labels:
    app: django-test-11
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
