apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-04-pvc
  namespace: django-test-04
  labels:
    app: django-test-04
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
