apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-12-pvc
  namespace: django-test-12
  labels:
    app: django-test-12
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
