apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-1-pvc
  namespace: django-test-1
  labels:
    app: django-test-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
