apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-argo-test-01-pvc
  namespace: django-argo-test-01
  labels:
    app: django-argo-test-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
