apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-13-pvc
  namespace: django-test-13
  labels:
    app: django-test-13
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
