apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-test-16-pvc
  namespace: django-test-16
  labels:
    app: django-test-16
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
